# Generated by Django 5.1.2 on 2025-03-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='CandidateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_read', 'Не просмотрено'), ('access', 'Документы приняты'), ('not_access', 'Документы не были посланы')], default='not_read', max_length=100, verbose_name='Статус документов')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат')),
            ],
            options={
                'verbose_name': 'Заявка кандидата',
                'verbose_name_plural': 'Заявки кандидатов',
            },
        ),
    ]
