# Generated by Django 5.1.2 on 2025-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaccess',
            name='status',
            field=models.CharField(choices=[('not_read', 'Не просмотрено'), ('access', 'Документы приняты'), ('not_access', 'Документы не были посланы'), ('give_enter', 'Приглашение')], default='not_read', max_length=100, verbose_name='Статус документов'),
        ),
    ]
