# Generated by Django 5.1.2 on 2025-04-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidateaccess_status'),
        ('judgment', '0005_alter_district_options_alter_judgment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaccess',
            name='judgment_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judgment.judgment'),
        ),
    ]
