# Generated by Django 5.1.2 on 2025-04-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidateaccess_judgment_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaccess',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
