# Generated by Django 5.1.2 on 2025-04-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidateaccess_candidate'),
        ('judgment', '0005_alter_district_options_alter_judgment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateaccess',
            name='judgment_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='judgment.judgment'),
        ),
    ]
