# Generated by Django 5.1.2 on 2025-04-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidateaccess_judgment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
