# Generated by Django 5.1.2 on 2025-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaccess',
            name='message_to_candidate',
            field=models.CharField(max_length=300, null=True, verbose_name='Сообщение кандидату'),
        ),
    ]
