# Generated by Django 5.1.2 on 2025-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidateaccess_message_to_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='telegram_id',
            field=models.CharField(max_length=255),
        )
    ]
