# Generated by Django 5.1.2 on 2025-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_candidate_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='telegram_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
