FROM python:3.12.3-slim

WORKDIR /app

COPY max_bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-c", "from max_bot import main_run; main_run()"]
# CMD ["sleep", "infinity"]
