# Generated by Django 5.1.2 on 2025-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0003_alter_judgment_inspector_delete_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='vacancies',
            field=models.ManyToManyField(blank=True, through='judgment.VacancyInJudgment', to='judgment.vacancy'),
        ),
    ]
