# Generated by Django 5.1.2 on 2025-03-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_judgment_vacancies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='judgment',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='vacancyinjudgment',
            options={'verbose_name': 'Вакансия в участке', 'verbose_name_plural': 'Вакансии в участке'},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание участка'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgment.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='fio_judgment',
            field=models.CharField(max_length=255, verbose_name='ФИО судьи'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='id_judgment',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер участка'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный инспектор'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон(ы) участка'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='vacancies',
            field=models.ManyToManyField(blank=True, through='judgment.VacancyInJudgment', to='judgment.vacancy', verbose_name='Вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancyinjudgment',
            name='judgment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgment.judgment', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='vacancyinjudgment',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgment.vacancy', verbose_name='Вакансия'),
        ),
    ]
