# Generated by Django 5.1.2 on 2024-10-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeUserWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата окна')),
                ('time_start', models.TimeField(verbose_name='Время начала окна')),
                ('time_end', models.TimeField(verbose_name='Время окончания окна')),
                ('status', models.CharField(choices=[('close', 'Запись закрыта'), ('open', 'Запись открыта')], default='open', max_length=255, verbose_name='Зарезервировано кандидатом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Окно времени',
                'verbose_name_plural': 'Окна времени',
            },
        ),
        migrations.CreateModel(
            name='TimeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_data', models.CharField(max_length=255, verbose_name='ФИО кандидата')),
                ('telegram_nickname', models.CharField(max_length=255, null=True)),
                ('id_judgement_place', models.IntegerField(verbose_name='Номер судебного участка')),
                ('taken_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeticket.timeuserwindow', verbose_name='Выбранное время')),
            ],
            options={
                'verbose_name': 'Зарезервированное окно',
                'verbose_name_plural': 'Зарезервированные окна',
            },
        ),
    ]
