# Generated by Django 5.1.2 on 2024-11-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeuserwindow',
            options={'permissions': (('can_see_own_record', 'Может просматривать только свои записи'),), 'verbose_name': 'Окно времени', 'verbose_name_plural': 'Окна времени'},
        ),
        migrations.AlterField(
            model_name='timeorder',
            name='telegram_nickname',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя в телеграмме'),
        ),
    ]
