# Generated by Django 5.1.2 on 2025-04-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('timeticket', '0002_alter_timeuserwindow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeorder',
            name='id_judgement_place',
        ),
        migrations.RemoveField(
            model_name='timeorder',
            name='person_data',
        ),
        migrations.RemoveField(
            model_name='timeorder',
            name='telegram_nickname',
        ),
        migrations.AddField(
            model_name='timeorder',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Кандидат'),
        ),
    ]
