# Generated by Django 5.1.2 on 2025-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeticket', '0003_remove_timeorder_id_judgement_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeorder',
            old_name='candidate',
            new_name='person_data',
        ),
    ]
